### ISSUE TITLE
Now Playing?

### ISSUE THREAD

**Issue by sbrooke** [axsuul/plex-media-server-exporter#15]
Thank you for putting this together! I've been looking for something that doesn't require InfluxDB. Any chance this can pull details on currently playing content? It has count, but I'm looking for details.

**Comment by axsuul** [comment]
Sorry, not at the moment but not sure if that's the best use case for that since content can be pretty unique. Have you tried using Tautulli instead for this?

**Comment by sbrooke** [comment]
I’ve used Varken with Tautulli, but it requires InfluxDB and I’m trying to avoid that. ScottOn Jan 21, 2024, at 4:00 PM, James Hu ***@***.***> wrote:﻿
Sorry, not at the moment but not sure if that's the best use case for that since content can be pretty unique. Have you tried using Tautulli instead for this?
