### ISSUE TITLE
Unable to connect via HTTPS when using self-signed certificate

### ISSUE THREAD

**Issue by timetinytim** [axsuul/plex-media-server-exporter#22]
I currently have my plex server set up to only allow secure connection. Because all connections go through Plex central first, there's no need to worry about making sure the endpoint on my side has a proper, verifiable SSL certificate. However, when the exporter tries to connect to plex, it fails when trying to verify the cert.

This manifests in the form of this particular error when trying to connect:
```
2024-12-22 11:22:01 +0100 Rack app ("GET /metrics" - (127.0.0.1)): #<ArgumentError: value must be a number>
```

I'm certain this is an SSL error though, as there is no issue when allowing insecure connections and connecting over HTTP.

**Comment by axsuul** [comment]
Closed by https://github.com/axsuul/plex-media-server-exporter/pull/23
