### ISSUE TITLE
Dashboard and image size

### ISSUE THREAD

**Issue by Kybeer** [axsuul/plex-media-server-exporter#7]
Thanks @axsuul for the Exporter!

I have two questions; 

Do you have any Grafana dashboard to share for it?

About the container image size, it's quite big - 963MB (bigger than the Plex server image itself). Not an issue, I was just wondering if it's by design.

thanks,

**Comment by axsuul** [comment]
Sure will look into this! Also yep never made an effort to optimize the Docker image — is this something that's important for you?

**Comment by axsuul** [comment]
Fixed by https://github.com/axsuul/plex-media-server-exporter/pull/8

**Comment by Kybeer** [comment]
> Sure will look into this! Also yep never made an effort to optimize the Docker image — is this something that's important for you?

No the size is not a real issue for now. I made a dashboard and will upload it to grafana.com

**Comment by axsuul** [comment]
> > Sure will look into this! Also yep never made an effort to optimize the Docker image — is this something that's important for you?
> 
> 
> 
> No the size is not a real issue for now. I made a dashboard and will upload it to grafana.com 

Great! I can also add it to the README. I also added an example dashboard to the README already.
